### ISSUE TITLE
The problem in the Documentation of Quick Sort Algorithm

### ISSUE THREAD

**Issue by Jils31** [TheAlgorithms/Python#11683]
### What would you like to share?

As this platform is for user to learn various algorithms by reading the code and documentation provided for any language, so in the Quick sort algorithm the code written for java is exited with errors without any updation, also errors are also showing for C language

https://github.com/user-attachments/assets/9b2012ff-2d0d-4185-8f01-1881e567577a

**Comment by tianyizheng02** [comment]
This sounds like it could either be an issue with the original code examples in the C and Java algorithm repos, or it could be an issue with the website's code playground. In any case, I recommend you open an issue at https://github.com/TheAlgorithms/website instead, since the maintainers of that repo are responsible for maintaining the website.

**Comment by karshav16** [comment]
Interested in contributing in this issue

**Comment by tianyizheng02** [comment]
Closing this issue since this is technically outside the scope of this repo. I hope you're able to get some help with this issue from the folks at the website repo.
