### ISSUE TITLE
strings/join.py is incorrect

### ISSUE THREAD

**Issue by osman-haider** [TheAlgorithms/Python#12408]
### Repository commit

3b1b70bf0e60dddb14917dd7cad34a41d429df01

### Python version (python --version)

Python 3.10

### Dependencies version (pip freeze)

n/a

### Expected behavior

s = ["", "", ""]
join(",", s) == ",".join(s)
# ',,' == ',,'

### Actual behavior

s = ["", "", ""]
join(",", s) == ",".join(s)
# '' != ',,'

**Comment by niralinayak** [comment]
The issue arises because you may have redefined or implemented your own version of the join function that does not behave as expected. The Python built-in str.join method works correctly, and you should ensure it is used instead of any custom implementation.

Here’s how you can fix the issue:

Check for redefinition of join: Ensure that the name join hasn’t been overridden in your code or by a module.

Solution code snippet:


s = ["", "", ""]
result = ",".join(s)
print(result)  # Outputs: ',,'
If you need a custom implementation of join: Ensure it mimics the behavior of str.join. Here’s an example:


def join(separator, iterable):
    return separator.join(iterable)

s = ["", "", ""]
print(join(",", s))  # Outputs: ',,'
Explanation of Built-in Behavior
The built-in str.join works by concatenating the strings in the iterable with the separator. An empty string "" is still a valid string, so ",".join(["", "", ""]) produces ",,".


If join is not behaving as expected:

Check if join has been redefined by adding a print statement: print(join).
Avoid using the name join for any variable or function that isn’t related to its intended use.

**Comment by snehagoyal25** [comment]
Can you assign this issue to me ?
