### ISSUE TITLE
Stuck in a get value issue

### ISSUE THREAD

**Issue by Corn3llius** [TheAlgorithms/Python#1623]
Hello all, 
I'm beginner in programming as you will observe as is follows. Hardly I succeed to make a trunk of software in python which can let you to insert some random numbers (only floats).
How ever I do not know how to store the values and call them when I need to make different operation as Sum, div etc.
I have tried with list and other function but not seams to work.
I do not know if the code which I have wrote is correct defined, maybe someone could take a look and give me some hints .

Please see the code bellow:

```
def b():
    num1 = False
    while not num1:
        try:
            V1 = a(x=True)
            if V1 == float(V1):
               num1 = True
        except ValueError:
            print('Please insert only numbers')


def a(x):
    x = float(input('Please insert Val '+str(count)+': '))
    return x

count = 1
n = int(input('Please insert number of elements : '))
while count <= n:
    b()
    count += 1
```

**Comment by onlinejudge95** [comment]
There are certain areas of improvement in your source code, please read along :)

1. You are making your code unnecessarily complex. As far as i can see from your question, what you want to do is
    - Read `floats` from `stdin` 
    - Store them in some data structure
    - Perform some arithmetic operation
I ran your code on my system and it runs fine up to 1st point. 
2. In order to advance further study how to store element in a list (you can also do some clever tricks to generate the result on the fly, but we will skip that route for now)
3. Lastly all you have to do is iterate on your list and perform the desired computation storing the intermediate result somewhere, maybe after that you can proceed with all sorts of combinations like, performing different operations each time and so on.

Do reach out in case of any issues

**Comment by Corn3llius** [comment]
Hi, 

Thanks, the iteration is the issue, I do not know how to create an entire list from an input variable...
Some how I want to give the size of the list using input "n" and after to insert and keep all the data from a() in that list, each time until the counter reach n max value...

wherever I search in documentation/books/ethernet, is the classic example with predefined list.

**Comment by Corn3llius** [comment]
Yesterday I have done 'it, and now it's work.
Here is the code until this moment:
def b():
    num1 = False
    while not num1:
        try:
            V1 = a()
            if V1 == float(V1):
               num1 = True
            return V1
        except ValueError:
            print('Please insert only numbers')
def a():
    x = float(input('Please insert Val '+str(count)+': '))
    return x
count = 1
n = int(input('Please insert number of elements : '))
list = []
while count <= n:
    list.append(b())
    count += 1
else:
    print (list)

**Comment by onlinejudge95** [comment]
Happy coding 🥳🥳

**Comment by onlinejudge95** [comment]
Now try to implement operating on the list elements.
