### ISSUE TITLE
[Project Euler] Algorithms do not follow coding styles

### ISSUE THREAD

**Issue by kalpanajangra** [TheAlgorithms/Python#2786]
Many algorithms in Project Euler do not follow coding styles as mentioned by @dhruvmanila [here](https://github.com/TheAlgorithms/Python/issues/2695#issuecomment-703122388), or even the standard coding guidelines.

Notes:
- A lot of inconsistencies with the `solution` functions (a lot of them aren't named as "solution")
- docstring inconsistencies:
```
>```docstring```
vs
>```
docstring```
```
- [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) says:
```
The following are considered to be bad and may be requested to be improved:
>>> x = x + 2	# increased by 2
This is too trivial. Comments are expected to be explanatory. For comments, you can write them above, on or below a line of code, as long as you are consistent within the same piece of code.
```
  But there are places where this isn't practised. https://github.com/TheAlgorithms/Python/blob/b934da4516a18814e2645413a20eedb3ac03a170/project_euler/problem_30/soln.py#L36
- Python typehints don't seem to be present in the initial problem solutions.
https://github.com/TheAlgorithms/Python/blob/b934da4516a18814e2645413a20eedb3ac03a170/project_euler/problem_01/sol1.py#L9 https://github.com/TheAlgorithms/Python/blob/b934da4516a18814e2645413a20eedb3ac03a170/project_euler/problem_01/sol2.py#L9
- Filename inconsistencies. [example](https://github.com/TheAlgorithms/Python/blob/master/project_euler/problem_30/soln.py)

The list isn't complete.
As a beginner who's looking to either understand/contribute, this makes it a bit difficult.

**Comment by dhruvmanila** [comment]
This is a completely valid issue. The thing is:
- Those initial solutions were submitted a long time ago
- I don't think consistency was maintained back then

Now as the number of solutions is increasing we need to enforce some of the consistency. One of the main ones was as I mentioned in https://github.com/TheAlgorithms/Python/issues/2695#issuecomment-703122388 but as you said there are many more. We can start with this and fix one issue at a time.

Due to some of the solutions not containing `solution()` function or requires some number of positional arguments we have decided to skip this [script](https://github.com/TheAlgorithms/Python/blob/master/project_euler/validate_solutions.py) for now which checks for the solutions for every problem present. We can start fixing this first and then move on to other issues mentioned. 

***Submit the fix for one directory at a time and once that is approved, submit another one.***

These are the errors which need to be fixed before we can start running the script in our tests:
https://travis-ci.com/github/TheAlgorithms/Python/jobs/394777235#L240-L312

These two are the main messages to look for in the above log:
1. `solution() missing 1 required positional argument: 'n'`
2. `module 'sol1.py' has no attribute 'solution'`

- The first one says that we have a `solution()` function but that requires a positional argument so to fix that put the default value for those parameters as the question input such that when we call the function without any arguments it returns the answer.
- The second one says that the specific file doesn't contain any `solution()` function so we need to either add the function or change the name of the present function, which returns the answer, to `solution()` and if it takes any positional arguments, to do the same thing as mentioned in the first point.

**Comment by M-Smits** [comment]
@dhruvmanila Is the task list up to date? 
Because I see a lot of commits and I am not sure where I can still help.

**Comment by dhruvmanila** [comment]
@M-Smits Yes, but keep in mind that the task list only removes a fix if it's merged. It might be the case that the fix is present in the list but someone already opened a PR, you have to confirm that yourself.

**Comment by UsmanAhmadSaeed** [comment]
@dhruvmanila I'm a beginner in Python and would love to contribute. Could you please guide me with any of the issues and I'll take it from there? 
Thanks

**Comment by manthan2501** [comment]
I would like to work on this in python. kindly assign me this work.

**Comment by dhruvmanila** [comment]
Thank you everyone for submitting the PR and fixing this issue in such a short amount of time.

There's only one file remaining to be fixed but that requires a lot of work, so if anyone's up for the challenge they are most welcomed: `problem_234/sol1.py`

There's one more issue which needs to be fixed which is regarding `mypy` which is going to be our next goal. I will open an issue in a few days and the instructions on how you can contribute. Stay tuned for that!
