### ISSUE TITLE
Create a Github Action to autoclose a PR (Conditions specified in description)

### ISSUE THREAD

**Issue by xcodz-dot** [TheAlgorithms/Python#3707]
The automated action should close a PR if:
* the other github actions fail and are not fixed within 7 days from latest commit of the PR (This closes PR which fail test and are left alone for 7 days)[**Exceptions include for draft pull request**]

**Comment by dhruvmanila** [comment]
I don't think so this is a valid condition. What we should do is to add a label and a comment about where to look for the errors in case of failure and encourage them to rectify their mistakes. This will all be done by the bot I'm creating currently and then the stale bot will come into place when the issue/pr remains inactive for 30 days. Unless and until the user asks for help, we don't need to interact with PR otherwise the number for stale bot will reset.
