### ISSUE TITLE
Unable to add more contributions

### ISSUE THREAD

**Issue by algobytewise** [TheAlgorithms/Python#4266]
I've been unable to add more contributions to this repository for almost 2 weeks since the algorithms-keeper-bot keeps closing my new pull requests because my earlier pull requests are still open. Is there a way to avoid this problem so I can contribute more?

**Comment by dhruvmanila** [comment]
Hi, sorry for your inconvenience but we did setup the bot to close the PRs once we reach a minimum threshold so that we can focus on a few pull requests at a time. Please give us more time to review your earlier pull requests and then you can open additional pull requests once the old ones gets merged.

**Comment by algobytewise** [comment]
Alright, thanks for the clarification.
