### ISSUE TITLE
Some files use print("", end="") from python 3.x which is not available by default in 2.x

### ISSUE THREAD

**Issue by mtarek** [TheAlgorithms/Python#47]
I thought it was only one file at the beginning, but it seems that several files use this print statement, so `from __future__ import print_function`  is needed for 2.x

**Comment by vsahil** [comment]
Would you be clear on what exactly needs to be done @mtarek

**Comment by ketakee** [comment]
I suppose @mtarek  is suggesting using from __future__ import print_function (for all the files or only for the files that use print("", end="")) , since print() is a part of python 3 and above and it won't work in python 2.x without explicitly importing it. I would suggest mentioning that the code runs on python 3.x or we could make it compatible by importing it but commenting it out and asking users to uncomment that line if running on python 2.x

**Comment by mtarek** [comment]
Sorry, that fell under my radar.

What @ketakee explained is mostly what I meant to say. I saw consistent use of print("", end="") in several files, and this is only available in 3.x. However, the code seems to try to be 2.x compatible also, for example:

```
    # For python 2.x and 3.x compatibility: 3.x has not raw_input builtin
    # otherwise 2.x's input builtin function is too "smart"
    if sys.version_info.major < 3:
        input_function = raw_input
    else:
        input_function = input
```

So, for python 2.x, this block should probably include an import for print_function, as @ketakee pointed out.

Something like:
```
    # For python 2.x and 3.x compatibility: 3.x has not raw_input builtin
    # otherwise 2.x's input builtin function is too "smart"
    if sys.version_info.major < 3:
       from future import print_function
        input_function = raw_input
    else:
        input_function = input
```

**Comment by harshildarji** [comment]
What?

**Comment by harshildarji** [comment]
What?

**Comment by 0oo0** [comment]
Can this be closed now?
