### ISSUE TITLE
Youtube_video_downloader

### ISSUE THREAD

**Issue by viswaamitcodes** [TheAlgorithms/Python#5332]
Hello,
-> I worked on small project that can download a video from youtube
-> can i share that?
-> If possible assign me this issue with Hactoberfest tags
Thank you

**Comment by andriyevski** [comment]
Nice add)

**Comment by SambariManikanta09** [comment]
Hello,
-> I worked on similar project, to download Youtube videos 
-> Uniqueness is that, it downloads the video at the high possible clarity
-> It is simple to use, you can any downloadable video just by using its link
-> This can be further enhanced by automating

**Comment by lnxpy** [comment]
Hey @viswaamitcodes,
I suggest you use your algorithms and modules in order to fix [youtube-dl](https://github.com/ytdl-org/youtube-dl) or [pytube](https://github.com/pytube/pytube) issues at the moment. Previously, I had run a Django-based project that was supposed to work with YT videos using pytube, but unbelievably stopped working for no reason. Same happened for a Telegram bot.
