### ISSUE TITLE
Fractional knapsack problem(greedy approach)

### ISSUE THREAD

**Issue by manan005** [TheAlgorithms/Python#5563]
Pease assign this to me under hacktober:)

**Comment by TakshakRamteke** [comment]
Is someone working on this ? if not then may I please work on this :slightly_smiling_face:

**Comment by Aditya-Gupta1** [comment]
If this is not being worked upon, I'll like to take this up.

**Comment by cclauss** [comment]
Please do not wait for permission to create the future that you want to live in.

We accept pull requests.

**Comment by Aditya-Gupta1** [comment]
As per my knowledge, general practice is to ask if the issue is not being worked on and upon confirmation, start working on it. Especially when the issue was created by some other person.

You could've simply asked me to submit a pull request, but you decided otherwise. Tells a lot about the future you're working to live in.

It was great talking to you and I'm done here.
