### ISSUE TITLE
Segmented Sieve of Eratosthenes - Feature Request + Assignment Request 

### ISSUE THREAD

**Issue by faizan2700** [TheAlgorithms/Python#8040]
### Feature description

I would like to implement segmented sieve of erathosthenes (and may be other variations of it). Please tell if you would merge that. And also let me know what other features, optimizations of algorithms or anything else you want. I would love to work on this repository. Let me know as soon as possible. I will start, as soon as I get the heads up. @cclauss

**Comment by Nomine-Nihil** [comment]
That's quite the merge there.

**Comment by cclauss** [comment]
Thanks, @tianyizheng02 -- Agreed.

Also, when contributing another implementation of an algorithm that we already have it is quite helpful to include a [`timeit` benchmark}(https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20timeit&type=code) so that visitors can compare the implementations.
