### ISSUE TITLE
Amazon Requests

### ISSUE THREAD

**Issue by thomasthaddeus** [TheAlgorithms/Python#8164]
### Repository commit

222715391-2b3d3a33-d553-481c-8577-56950e913eaf

### Python version (python --version)

python 3.9

### Dependencies version (pip freeze)

python=3.9
requests not in loader

### Expected behavior

I'm not exactly sure other than I loaded it on the website, and this was the default behavior.

### Actual behavior

[![image](https://user-images.githubusercontent.com/92204097/222715391-2b3d3a33-d553-481c-8577-56950e913eaf.png)](https://the-algorithms.com/playground?id=6869)

**Comment by watrgoat** [comment]
Have you installed all of the requirements from the requirements.txt file?
If you don't know how to do this navigate to you command line inside the file directory where this repo is and type: `pip install -r requirements.txt`

And which file are you trying to run. From the title I am guessing this is the get_amazon_product_data.py file

And as you aren't sure what the expected behavior is, it seems that it should give you a csv file with all of the amazon product data for the product type searched, which you can change to whatever search you want at the end.

**Comment by thomasthaddeus** [comment]
this is on the webpage for this [repo](https://the-algorithms.com/algorithm/get-amazon-product-data). Is the try this function not working
![image](https://user-images.githubusercontent.com/92204097/224512149-3ed88e69-d07f-4622-907f-3a843803ccd8.png)

**Comment by watrgoat** [comment]
I see, it doesn't work for me either. In this case if you want to use the code then I guess just try it out on your own machine until they fix this.

**Comment by thomasthaddeus** [comment]
Should the issue stay open as a website issue or is there a better way of classifying the bug

**Comment by watrgoat** [comment]
I think but am not 100% that you should instead add this as an issue to the [website repo here](https://github.com/TheAlgorithms/website)
And add all of the info that we discussed so they understand the problem better.

**Comment by thomasthaddeus** [comment]
I quoted everything in this issue and posted it along with the photos on that repo.

I'm going to close it here because I didn't realize the other repo existed.

Closes #8164

**Comment by Yashdighe** [comment]
Stop it

**Comment by thomasthaddeus** [comment]
?
