### ISSUE TITLE
Pre-commit auto-updates break ruff

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#8877]
### What would you like to share?

In these failing tests, algorithms that have not been touched are broken due to the latest pre-commit update (https://github.com/TheAlgorithms/Python/commit/5aefc00f0f1c692ce772ddbc616d7cd91233236b)

https://github.com/TheAlgorithms/Python/actions/runs/5629561962/job/15254651560?pr=8875

Perhaps the reason of this error is that when the pre-commit pull request is made, the pre-commit file is changed, however the tests run from the old .pre-commit-config, not the new, changed one. This can be shown in the pr #8878, where the tests supposedly fail, when reverting the commit

**Comment by CaedenPH** [comment]
@cclauss I don't think this should be closed. This issue raises the point that this is not just the first time that this has happened, but that it seems that the autoupdates pass the tests but then break pull requests. This is still very much a problem, but I can't reopen this issue because you closed it

**Comment by cclauss** [comment]
Ruff is not alone... We [do not pin any of our dependencies](https://github.com/TheAlgorithms/Python/blob/master/requirements.txt).  We do this on purpose because we are not building a single application and reproducible builds are not important here.  Instead, we are an "active community" with "well-tested" algorithms where we want our tests + CI to inform us when an upgrade to _any_ dependency breaks our code.  This helps us understand breakage and contribute new issues and fixes to those dependencies.  I know of at least one instance where kind of work has led to paid positions for active contributors to this repo.

The special issue with `ruff` is that we run it two different ways and those two can be out-of-sync on ruff versions.
* `.github/workflows/ruff.yml` is designed to run superfast (~ 5sec) and provide GitHub Annotations to contributors.
* `.pre-commit-config.yaml` is designed to run automatically both locally and in CI without added `--format=github`

This means that when creating a pull request to fix the former, a contributor must also update the version in the latter.

Do you have a better solution that does not sacrifice the goals above?
