### ISSUE TITLE
Added Uniform Cost Search Algorithm

### ISSUE THREAD

**Issue by Miltonbhowmick** [TheAlgorithms/Python#8941]
### Feature description

I am happy to pass all 3 checks for testing after several tried via contribute guide. Its my first try for adding new algorithm in python community. I don't know about the awaiting review label. Anyone is for review my PR? I will make the code more elegant and readable in future too.

PR: https://github.com/TheAlgorithms/Python/pull/8931

**Comment by tianyizheng02** [comment]
Hi @Miltonbhowmick, thanks for your contribution. I've already taken a note of your PR, but I haven't gotten the chance to fully review it, as it's a fairly large PR. There is currently an enormous backlog of PRs and we maintainers work on a volunteer basis, so it can take a while until one of us gets the chance to review any given PR. At the moment, I'm prioritizing reviewing smaller and "easier" PRs in order to clear out the backlog ASAP. We're hoping to get to your PR soon, and we'd appreciate it if you could be patient with us in the meantime.

**Comment by Miltonbhowmick** [comment]
> Hi @Miltonbhowmick, thanks for your contribution. I've already taken a note of your PR, but I haven't gotten the chance to fully review it, as it's a fairly large PR. There is currently an enormous backlog of PRs and we maintainers work on a volunteer basis, so it can take a while until one of us gets the chance to review any given PR. At the moment, I'm prioritizing reviewing smaller and "easier" PRs in order to clear out the backlog ASAP. We're hoping to get to your PR soon, and we'd appreciate it if you could be patient with us in the meantime.

Thank you so much for your time. I have given a fresh PR.
