### ISSUE TITLE
Suggestion: Why not refactor the source codes using Numpy?

### ISSUE THREAD

**Issue by CHRIBUR0309** [TheAlgorithms/Python#9029]
### Feature description

I saw just several source codes here and I found you can refactor some of them using Numpy. I think you should put the codes of both: pure Python and Numpy-refactored.

**Comment by rohan472000** [comment]
Can you point out exactly which code are you talking about?

**Comment by quant12345** [comment]
@CHRIBUR0309 @rohan472000 

My code does refactor and optimization. And I also think that solutions should be left in pure Python, since Numpy is less visually understandable and perhaps someone will want to apply numba to the code and it will not work with all the functions of Numpy. 

Need both options: pure Python (slow) and Numpy (fast).

I basically did this in my pull request. And I can do more. But so far there is no movement on it, so enthusiasm is drying up.

**Comment by rohan472000** [comment]
@quant12345 give me the PR no. or link of it..

**Comment by quant12345** [comment]
> @quant12345 give me the PR no. or link of it..

https://github.com/TheAlgorithms/Python/pull/8938

**Comment by rohan472000** [comment]
Close it as #8938 is merged.

**Comment by ClariNerd617** [comment]
> @CHRIBUR0309 @rohan472000 
> 
> 
> 
> My code does refactor and optimization. And I also think that solutions should be left in pure Python

I thought this repository was supposed to demonstrate best-practices. If numpy provides a better solution that is suggested on a regular basis, then PEP-20 clearly states there should be one and only one obvious solution.

**Comment by cclauss** [comment]
[`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#issues) says:
> __Do not__ create an issue to contribute an algorithm. Please submit a pull request instead.
