### ISSUE TITLE
Adding is_odd code using bit manipulation

### ISSUE THREAD

**Issue by siddwarr** [TheAlgorithms/Python#9346]
### Feature description

We can use bit manipulation to determine whether a number is odd. Currently this code does not exist under bit manipulation so it will be helpful if we add that to the folder

**Comment by piyush-poddar** [comment]
Hi I have raised a [PR](https://github.com/TheAlgorithms/Python/pull/9708), please review it.
I added the is_odd code using bit manipulation and also updated the DIRECTORY.md file accordingly.

**Comment by tianyizheng02** [comment]
@cclauss has said in #9470 that we have no need for this algorithm because it's far, far too simple to be of much value. This could be done in a single line of code. Plus, we already have [bit_manipulation/is_even.py](https://github.com/TheAlgorithms/Python/blob/d74349793b613b0948608409a572426a9800c3a1/bit_manipulation/is_even.py), which eliminates the need for an "is odd" algorithm anyway.

@cclauss, given that we don't want this algorithm because it's just a one-liner, shouldn't we also delete the existing `is_even.py`? It's just a one-liner as well.

**Comment by cclauss** [comment]
Let's not accept this one but also, let's not remove things that have landed unless the are really problematic.  Our standards have gone up over the years but we should be careful about destroying contributions that have merged.
